### PR TITLE
feat: add Chinese Translation 

### PR DESCRIPTION
**Pull request by weihao**
following up on #158

not sure why you merged from the main to chinese branch.

It should be merging a feature branch into the main branch.

Chinese translation file LGTM

### CODE REVIEW

**Comment by pdinklag** [comment]
> following up on #158
> 
> not sure why you merged from the main to chinese branch.
> 
> It should be merging a feature branch into the main branch.

The Zpix font that was committed there is not working in any of my browsers due to "OTS parsing errors" and I never got a reply from @imsalze. I don't know what the issue is or how to fix it, so I'll try again with your version and have a try with the font.

**Comment by weihao** [comment]
> > following up on #158
> > not sure why you merged from the main to chinese branch.
> > It should be merging a feature branch into the main branch.
> 
> The Zpix font that was committed there is not working in any of my browsers due to "OTS parsing errors" and I never got a reply from @imsalze. I don't know what the issue is or how to fix it, so I'll try again with your version and have a try with the font.

Worked for me and I have deployed the feature on a live website.

**Comment by pdinklag** [comment]
> > > following up on #158
> > > not sure why you merged from the main to chinese branch.
> > > It should be merging a feature branch into the main branch.
> > 
> > 
> > The Zpix font that was committed there is not working in any of my browsers due to "OTS parsing errors" and I never got a reply from @imsalze. I don't know what the issue is or how to fix it, so I'll try again with your version and have a try with the font.
> 
> Worked for me and I have deployed the feature on a live website.

I will merge this into branch `chinese-2` now and check it again.
If there are parsing errors again, I'll let you know here. Can you provide a link to your instance so I can check if it works there too? It may be a configuration thing somewhere, but since the author of the other PR never replied, I do not know.

**Comment by pdinklag** [comment]
OK, the font is still not working here in Chrome. I will check Firefox later but last time it had the same issue. I get the following warnings in the console:
```
?lang=zh-hans:1 Failed to decode downloaded font: http://mine3.dvgaming.com/font/CJK_Zpix.woff2
?lang=zh-hans:1 OTS parsing error: OS/2: Failed to parse table
```

Can you go here and check for yourself? http://mine3.dvgaming.com/?lang=zh-hans
And also please provide a link where it's working for you so I can verify.

Maybe it's an issue with non-Chinese browsers, I don't know. But I'd like this to be resolved before I'm merging into master.

**Pull request merged**
