### PR TITLE
feat: add Chinese translation JSON and selector on page

### PR DESCRIPTION
**Pull request by weihao**
continue on #178

Chinese Font added by the previous contributor does not work and I am able to reproduce the error. Also, I am unable to find any info about the font, so to be safe I removed it in the MR because of unknown copyright and source.

### CODE REVIEW

**Comment by weihao** [comment]
@pdinklag Please review the MR.  


I checked the minimized js files but make sure to double-check it again. 
People could sneak in malicious code if inattentive.

**Comment by pdinklag** [comment]
> continue on #178
> 
> Chinese Font added by the previous contributor does not work and I am able to reproduce the error.

I don't get it. A few days ago [you said](https://github.com/pdinklag/MinecraftStats/pull/178#issuecomment-956469031) it's working fine in #178 and now it's not? How was it working then, did you use a different version? Do you have a URL to the working instance?

I'd really like to find this out, because the usual smooth fonts really don't fit the style. That's OK for now, but it'd be cool to get the Zpix font or a similar font to work.

> Also, I am unable to find any info about the font, so to be safe I removed it in the MR because of unknown copyright and source.

It wasn't hard to find it really: https://github.com/SolidZORO/zpix-pixel-font
The license isn't the nicest, but also not a huge problem since MinecraftStats isn't a commercial product.

> @pdinklag Please review the MR.
> 
> People could sneak in malicious code if inattentive.

I usually regenerate it anyway, but thanks.

**Comment by weihao** [comment]
> > continue on #178
> > Chinese Font added by the previous contributor does not work and I am able to reproduce the error.
> 
> I don't get it. A few days ago [you said](https://github.com/pdinklag/MinecraftStats/pull/178#issuecomment-956469031) it's working fine in #178 and now it's not? How was it working then, did you use a different version? Do you have a URL to the working instance?
> 
> I'd really like to find this out, because the usual smooth fonts really don't fit the style. That's OK for now, but it'd be cool to get the Zpix font or a similar font to work.
> 
> > Also, I am unable to find any info about the font, so to be safe I removed it in the MR because of unknown copyright and source.
> 
> It wasn't hard to find it really: https://github.com/SolidZORO/zpix-pixel-font The license isn't the nicest, but also not a huge problem since MinecraftStats isn't a commercial product.
> 
> > @pdinklag Please review the MR.
> > People could sneak in malicious code if inattentive.
> 
> I usually regenerate it anyway, but thanks.

I thought the fonts are working but in fact, it was not pixelated and I didn't check the console. 

Also thanks for the link, and that's an interesting find. I am looking to add it to the feature

**Comment by weihao** [comment]
Font loaded correctly after the commit https://github.com/pdinklag/MinecraftStats/pull/179/commits/24c8eaef2e1b8da94296e73c0b040737f858b1e2

image


However, a problem surfaced that the `a` text inside of the `div` is not centered vertically, therefore it is not leveled with the icon.

It is just a minor issue in the presentation.

**Comment by imsalze** [comment]
> continue on #178
> 
> 
> 
> 
> 
> Chinese Font added by the previous contributor does not work and I am able to reproduce the error. Also, I am unable to find any info about the font, so to be safe I removed it in the MR because of unknown copyright and source.

Hello, FYI:

This is the [repository](https://github.com/SolidZORO/zpix-pixel-font) of this font on GitHub.

**Comment by weihao** [comment]
@pdinklag ping: please review PR

**Comment by pdinklag** [comment]
As per my Discord messages, I still cannot get the font to work, the browser still refuses to parse the font with the same messages as before (`OTS parsing error: OS/2: Failed to parse table`). 

This is running your `weihao:patch` branch right now:
http://mine3.dvgaming.com/?lang=zh-hans

Feel free to provide a link to an installation where it works for you, then I can give it a try there. Apparently it is working for you, after all? If we can't get the font to work, we can also just drop it for now and use the browser's default font until somebody manages to get Zpix to work, just so we can get the translation merged finally.

**Comment by weihao** [comment]
> As per my Discord messages, I still cannot get the font to work, the browser still refuses to parse the font with the same messages as before (`OTS parsing error: OS/2: Failed to parse table`).
> 
> This is running your `weihao:patch` branch right now: http://mine3.dvgaming.com/?lang=zh-hans
> 
> Feel free to provide a link to an installation where it works for you, then I can give it a try there. Apparently it is working for you, after all? If we can't get the font to work, we can also just drop it for now and use the browser's default font until somebody manages to get Zpix to work, just so we can get the translation merged finally.

I was able to solve the font issue. If you want more details: https://github.com/SolidZORO/zpix-pixel-font/issues/45

Please give it another try and review this PR @pdinklag

**Pull request merged**
